<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><PublishAot>false</PublishAot><PublishTrimmed>false</PublishTrimmed><PublishSingleFile>false</PublishSingleFile></PropertyGroup>
  <ItemGroup><ProjectReference Include="../AssetExport/AssetExport.csproj" /></ItemGroup>
</Project>
